//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 11:36:33 AM BST 
//


package ibm.soatest.config.osb;

import ibm.soatest.config.osb.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Attribute identificator is used for execution of framework component command or which object will be used for execution of the supported command.
 * 
 * <p>Java class for AdminServer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminServer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="managementMBeanServer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="managementMBeanService" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="initialContextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jmxProtocolProviderPackages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jmxServiceJNDIConstant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seesionNamePrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jmxProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="securityPrincipal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityCredentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="identificator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminServer", propOrder = {
    "managementMBeanServer",
    "managementMBeanService",
    "initialContextFactory",
    "jmxProtocolProviderPackages",
    "jmxServiceJNDIConstant",
    "seesionNamePrefix",
    "jmxProtocol",
    "host",
    "port",
    "securityPrincipal",
    "securityCredentials"
})
public class AdminServer {

    @XmlElement(required = true, defaultValue = "weblogic.management.mbeanservers.domainruntime")
    protected String managementMBeanServer;
    @XmlElement(required = true, defaultValue = "com.bea:Name=DomainRuntimeService,Type=weblogic.management.mbeanservers.domainruntime.DomainRuntimeServiceMBean")
    protected String managementMBeanService;
    @XmlElement(required = true, defaultValue = "weblogic.jndi.WLInitialContextFactory")
    protected String initialContextFactory;
    @XmlElement(required = true, defaultValue = "weblogic.management.remote")
    protected String jmxProtocolProviderPackages;
    @XmlElement(required = true, defaultValue = "/jndi/")
    protected String jmxServiceJNDIConstant;
    @XmlElement(required = true, defaultValue = "SoaTestingFramework")
    protected String seesionNamePrefix;
    @XmlElement(required = true, defaultValue = "t3")
    protected String jmxProtocol;
    @XmlElement(required = true)
    protected String host;
    protected int port;
    @XmlElement(required = true)
    protected String securityPrincipal;
    @XmlElement(required = true)
    protected String securityCredentials;
    @XmlAttribute(name = "identificator")
    protected String identificator;

    /**
     * Gets the value of the managementMBeanServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementMBeanServer() {
        return managementMBeanServer;
    }

    /**
     * Sets the value of the managementMBeanServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementMBeanServer(String value) {
        this.managementMBeanServer = value;
    }

    /**
     * Gets the value of the managementMBeanService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementMBeanService() {
        return managementMBeanService;
    }

    /**
     * Sets the value of the managementMBeanService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementMBeanService(String value) {
        this.managementMBeanService = value;
    }

    /**
     * Gets the value of the initialContextFactory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialContextFactory() {
        return initialContextFactory;
    }

    /**
     * Sets the value of the initialContextFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialContextFactory(String value) {
        this.initialContextFactory = value;
    }

    /**
     * Gets the value of the jmxProtocolProviderPackages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxProtocolProviderPackages() {
        return jmxProtocolProviderPackages;
    }

    /**
     * Sets the value of the jmxProtocolProviderPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxProtocolProviderPackages(String value) {
        this.jmxProtocolProviderPackages = value;
    }

    /**
     * Gets the value of the jmxServiceJNDIConstant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxServiceJNDIConstant() {
        return jmxServiceJNDIConstant;
    }

    /**
     * Sets the value of the jmxServiceJNDIConstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxServiceJNDIConstant(String value) {
        this.jmxServiceJNDIConstant = value;
    }

    /**
     * Gets the value of the seesionNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeesionNamePrefix() {
        return seesionNamePrefix;
    }

    /**
     * Sets the value of the seesionNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeesionNamePrefix(String value) {
        this.seesionNamePrefix = value;
    }

    /**
     * Gets the value of the jmxProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxProtocol() {
        return jmxProtocol;
    }

    /**
     * Sets the value of the jmxProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxProtocol(String value) {
        this.jmxProtocol = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    public int getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    public void setPort(int value) {
        this.port = value;
    }

    /**
     * Gets the value of the securityPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPrincipal() {
        return securityPrincipal;
    }

    /**
     * Sets the value of the securityPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPrincipal(String value) {
        this.securityPrincipal = value;
    }

    /**
     * Gets the value of the securityCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCredentials() {
        return securityCredentials;
    }

    /**
     * Sets the value of the securityCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCredentials(String value) {
        this.securityCredentials = value;
    }

    /**
     * Gets the value of the identificator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificator() {
        return identificator;
    }

    /**
     * Sets the value of the identificator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificator(String value) {
        this.identificator = value;
    }

}
