//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config.osb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ibm.soatest.config.osb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ibm.soatest.config.osb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link OSBConfiguration }
     * 
     */
    public OSBConfiguration createOSBConfiguration() {
        return new OSBConfiguration();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link AdminServer }
     * 
     */
    public AdminServer createAdminServer() {
        return new AdminServer();
    }

    /**
     * Create an instance of {@link ibm.soatest.config.osb.ManagedServer }
     * 
     */
    public ibm.soatest.config.osb.ManagedServer createManagedServer() {
        return new ibm.soatest.config.osb.ManagedServer();
    }

    /**
     * Create an instance of {@link Cluster.ManagedServer }
     * 
     */
    public Cluster.ManagedServer createClusterManagedServer() {
        return new Cluster.ManagedServer();
    }

}
