//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 02:56:41 PM BST 
//


package ibm.soatest.config.global;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GlobalConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileSystemStructure" type="{http://www.archenroot.org/SoaTestingFramework/GlobalConfiguration}FileSystemStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalConfiguration", propOrder = {
    "fileSystemStructure"
})
public class GlobalConfiguration {

    @XmlElement(required = true)
    protected FileSystemStructure fileSystemStructure;

    /**
     * Gets the value of the fileSystemStructure property.
     * 
     * @return
     *     possible object is
     *     {@link FileSystemStructure }
     *     
     */
    public FileSystemStructure getFileSystemStructure() {
        return fileSystemStructure;
    }

    /**
     * Sets the value of the fileSystemStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileSystemStructure }
     *     
     */
    public void setFileSystemStructure(FileSystemStructure value) {
        this.fileSystemStructure = value;
    }

}
