//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config.jms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * JMS messaging related configuration type.
 *             
 *             
 * 
 * <p>Java class for JMSConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JMSConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="server" type="{http://www.archenroot.org/SOATestingFramework/Config/JMS}JMSServer" maxOccurs="unbounded"/>
 *         &lt;element name="module" type="{http://www.archenroot.org/SOATestingFramework/Config/JMS}JMSModule" maxOccurs="unbounded"/>
 *         &lt;element name="fileSystemStructure" type="{http://www.archenroot.org/SOATestingFramework/Config/JMS}FileSystemStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JMSConfiguration", propOrder = {
    "server",
    "module",
    "fileSystemStructure"
})
public class JMSConfiguration {

    @XmlElement(required = true)
    protected List<JMSServer> server;
    @XmlElement(required = true)
    protected List<JMSModule> module;
    @XmlElement(required = true)
    protected FileSystemStructure fileSystemStructure;

    /**
     * Gets the value of the server property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the server property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JMSServer }
     * 
     * 
     */
    public List<JMSServer> getServer() {
        if (server == null) {
            server = new ArrayList<JMSServer>();
        }
        return this.server;
    }

    /**
     * Gets the value of the module property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the module property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JMSModule }
     * 
     * 
     */
    public List<JMSModule> getModule() {
        if (module == null) {
            module = new ArrayList<JMSModule>();
        }
        return this.module;
    }

    /**
     * Gets the value of the fileSystemStructure property.
     * 
     * @return
     *     possible object is
     *     {@link FileSystemStructure }
     *     
     */
    public FileSystemStructure getFileSystemStructure() {
        return fileSystemStructure;
    }

    /**
     * Sets the value of the fileSystemStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileSystemStructure }
     *     
     */
    public void setFileSystemStructure(FileSystemStructure value) {
        this.fileSystemStructure = value;
    }

}
