//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 11:36:33 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.archenroot.org/SoaTestingFramework/Config/JMS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ibm.soatest.config.jms;
