INSERT INTO XXXIW_MW_PO_VENDOR_CONTS_EXT (STAGING_HEADER_ID,INT_CONC_REQ_ID,INT_STATUS,SEQUENCE_NUM,ACTION_FLAG,VENDOR_CONTACT_ID,VENDOR_SITE_ID,VENDOR_ID,VENDOR_CODE,FIRST_NAME,MIDDLE_NAME,LAST_NAME,EMAIL_ADDRESS,FAX_AREA,FAX,AREA_CODE,PHONE,INACTIVE_DATE,VENDOR_SITE_CODE,ORG_ID,ORGANIZATION_CODE,MW_INT_NAME,MW_SOURCE_MESSAGE_REF,MW_SOURCE_ENTITY_REF,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,LAST_UPDATE_LOGIN
) VALUES (
    /*STAGING_HEADER_ID*/      4343843
    /*INT_CONC_REQ_ID*/       ,4343843
    /*INT_STATUS*/            ,'V'
    /*SEQUENCE_NUM*/          ,4343843
    /*ACTION_FLAG*/           ,'a'
    /*VENDOR_CONTACT_ID*/     ,196831191
    /*VENDOR_SITE_ID*/        ,1205591901
    /*VENDOR_ID*/             ,1539898740
    /*VENDOR_CODE*/           ,'sVmaeTRGowbHyohGviUuHNYjilQwzx'
    /*FIRST_NAME*/            ,'YslYIMnKHeMsdtc'
    /*MIDDLE_NAME*/           ,'lrHGfPPiqjwClfJ'
    /*LAST_NAME*/             ,'ybwNrhLLTKSdwnmBdPjJ'
    /*EMAIL_ADDRESS*/         ,'ZNTToZKOCyjiZasyQfDukScxldcDfsbLOkKLAnyAVbdJKveHTpVMLrNmnIRTPGCaomLMrDotTotzGSvGmApFnXEAdMNrHohkkCLaLdjevmrqYMGJQXcdKKzFUrlnlWNhVlJZOHrLNPCsmUfMiIxYtxWPbUNUwpMlMYomjjcjmgfIDLeBLZGDIsXOrHVQYAwjpFzjuBPbulPKvYouojJdIlIArncZtkoYrFvqPIvHYOXSyXjvECDerqsmUSgarEBXTkQKJQkasfWlsNWaMSnCOzrLdKvWesqpcGaDiKrBMQjlxtmobXHNqbOlfQeImBzOfrEJlVqXhptsVclYKxRHxGMhiggpLHoRTrzJyNbhyJVpgxScdPqdxlNvBqXmxoODMVLZdXGbcKjAWUZRLjGtQTeqAmxscWgIsncPSvJJCKiBLCPnwEpVzdhPMsrlkRmIFDxyhjSmJjHsvCaFFVaQHOsJhgBjNcImPbsKWiwrQrbmrldsefyyLazlWWiZsjvCfxfbtRMvtjDhBCZfyDNTGiozkNHsLjqeUeThaqJkEfmXKFQwOLbsqtZDuzIqbDGgrOvNBsbrmbDveLRcVAwThzdgpqdockdQgNVuXUeLGjdJuTQCoyDuJJxPATavTZtglLLPSNretfFZoKtkmlhsZvwrQbKieWhWxUGGrcNRjKvAFrxjQEGxpYKFIIrxSQyyyQCHmQkTTSiUCDTOZFuxsQHJZDvYIaTqViSwUFEdJhQvZYEvSjwVIfsKioObihAotEQiPgeLTVTkwdSjSdxDEWvhQTSLyIdkGQWSQAtEucAvdbrBWFhRMlHCefZKqzKDCIZnEWhVIrzEKgzntpYCITdRBiEqczgNOSEFpFPatCfbFwciMWGiskPBVvXeWvKOFfpMVhyXARRxUSgNTIKNIwMCRZKWiotFAvKYmrazaMVEBiqRxTdHsBcyFFUarhMnyWoZqvDOGPvqSdCqfbrVQIjnWgDfYyzcUsvADzyahevyiOVfokENIXSVEUFjLoaLpdivnVCdfQkIBOKNYarlAlUyeeOYrGpBTNDEEVLLvHDMmAxoEwyUsvOctWURkdltOHIyUOhGddwXzUTLgcHSwgGbAIBahMNEnpCiisFraUvDHvSjboebNQiBEIfjMHmWaNNGJEmRNSMSmskouapghEiAYVbAQrevygETfxpuMYaHgLdpwUSHtbcUZJwWxvfyDTAGLzIbcqayxRvjunrWRuGWKXdLzMBIqMNWtvtMTscvwWkmsPyMSgXCcSJRGZSIbYLbZAsUJuAPrUTZwMDtyubIWvZbOjwzBLeJenjAFwVcNKVFZWctWjXPhvRhvsedVJBwSPEsceUoyZIuNpvojLSIlMIDFXodmZpowZuHJLpGWHqPIBBvrTcnhnwmIBTVNJKKswhKllwSisHVrJuIUiqLVYrYItqmNIElaUuwnSZMAqJvujuBUYedmbePhIpPzBftGGcWcAXYRQCvoBwlRuGgQrZqPYRCmBmasBvELdTbNvByhAVAJkiBeybVrMFbLpKgEVrelypnIdHjndBDqMkskTpMXlpspLDbOHFTNTZajeeIHGocXtihsNonMWRTpMlcbrcAssCLYVYSTAGNLgbjPehTikiozAnZxkVsalKGAaNBvbOQULsTEIDfiiuRWHWMJWqwiNXPrWzomnpvVeccMkgimQokaZKcXRlEQCVLGsckRYPZxDvzGeOOzLVJUmHxDSBjNnmQHEfwjlnjyVtYzCDKGSfeEtxAKFjLFHIgsbBNpwjHTZDOmEbjRWttZkjTisJVrslKPAcrnTJSoBDGhokbqyfyLVScsqdgUwCmqgCloYiRBpUQkyMojCunAZatxsreromgvymIEdmvKvTboJUtqrVGdhnUrwRXAkAoUnJIYrdYXSmAhnsldwgjtjcQIONNFQfLvlWtAqqYoXMTumciSeXftYqmWNKGsUYjeLxyPyaHVQRsrYPEIsnmscNwrpVHtknOwSCr'
    /*FAX_AREA*/              ,'QVeCNwcmtj'
    /*FAX*/                   ,'SktdDpnEhGDsFnE'
    /*AREA_CODE*/             ,'EousxMxFXX'
    /*PHONE*/                 ,'UaxHeRtkmSEzTPd'
    /*INACTIVE_DATE*/         ,TO_DATE('2013/11/01 15:01:53', 'YYYY/MM/DD HH24:MI:SS')
    /*VENDOR_SITE_CODE*/      ,'JhpwDBdGJuOoUgK'
    /*ORG_ID*/                ,1477171329
    /*ORGANIZATION_CODE*/     ,'tgIMbcinQSBALQbnyFHceBVGzRPlxtIOFMKVFYQKfnWWFdWNKIfdWGvbfDQNIHgoHmjPjQYBybThzFfokndxbWDNSaNECBVRNPWFxVkotzrBWqdTiKCzmVTMePZDbvMrtrvkGnedkeaUyarHCWkwSD'
    /*MW_INT_NAME*/           ,'sbBROaNqXaWMwVYehLtfCVBCkfRrxaYHPcQVQuZvgUukXaFneTEmwWWamofSwACszbRzFheMbCsbeiEBUqoZnvfoyWzUMbHYKggJDKgbyuGbxppsdqDaHhWLeZYjSXgqRvBpMxGLLAfnifDfsRPbzXokoFxJFBVjMrsRsuUagKjbMpfeYIDWjJdOpNhAxAVqnyGzGGwkqmaTEuBiXqrtjzcuJuBtbEtgmudZSssCxuoDgKRDvBregWSnsAOBqFZ'
    /*MW_SOURCE_MESSAGE_REF*/ ,'ETKaEsWLRgLioHdSHCbBswxayTQXOKARlbdvXVvCBQApINkrVJAuayknDNDwCOqQxvBRlRJcRRDwBeKVJHIOeIqaTTPgCNsFSDhvlrtIOrLWoPSafqerRnhleLaYVVrTenrZQQacUbWgwXcXzworKjmaMidvvXKcinSUQTRSqvTdKcBkQIFGNzszEhkZxLyXxoOjUlWzFZGKcMBCHGBbnUFhnGkLpMmzNUnDMWIfxUOZYnTToSAOvqRMhTHohDL'
    /*MW_SOURCE_ENTITY_REF*/  ,'URKziQycLAvbLVnoJfYSTUvqNJzSptmCWMKFWSTUiYlwDGtKfQVozHOEjbFJGCaRNMtVrfWgYOwQnpDQhdczcmiXZmewvIyPJSswDhTHMPkgEwXCBUULMkBnMdyhisAzzBftHNmFqiJfCprNFvmKJCxXfVAsUjzZeVFArekCHvamBASHBOWXFpdxCxqYpwDNjyDqiqbmOLQRJnRuwbnwmOFUKVBKRlxzVpwvGnxlcIPTeYGAekeVNUdZqBUZrEz'
    /*CREATED_BY*/            ,670401728
    /*CREATION_DATE*/         ,TO_DATE('2013/11/01 15:01:53', 'YYYY/MM/DD HH24:MI:SS')
    /*LAST_UPDATED_BY*/       ,804107548
    /*LAST_UPDATE_DATE*/      ,TO_DATE('2013/11/01 15:01:53', 'YYYY/MM/DD HH24:MI:SS')
    /*LAST_UPDATE_LOGIN*/     ,630273293
);