//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 02:56:41 PM BST 
//


package ibm.soatest.config.databaseconfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * 		Configuration related to DatabaseComponent part of the framework.
 *                 
 *                 Supported databases: Oracle
 *                 
 *                 Planned support for any database with generic JDBC interface available.
 *                 
 *             
 * 
 * <p>Java class for DatabaseConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatabaseConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="database" type="{http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration}Database" maxOccurs="unbounded"/>
 *         &lt;element name="fileSystemStructure" type="{http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration}FileSystemStructure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatabaseConfiguration", propOrder = {
    "database",
    "fileSystemStructure"
})
public class DatabaseConfiguration {

    @XmlElement(required = true)
    protected List<Database> database;
    @XmlElement(required = true)
    protected FileSystemStructure fileSystemStructure;

    /**
     * Gets the value of the database property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the database property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Database }
     * 
     * 
     */
    public List<Database> getDatabase() {
        if (database == null) {
            database = new ArrayList<Database>();
        }
        return this.database;
    }

    /**
     * Gets the value of the fileSystemStructure property.
     * 
     * @return
     *     possible object is
     *     {@link FileSystemStructure }
     *     
     */
    public FileSystemStructure getFileSystemStructure() {
        return fileSystemStructure;
    }

    /**
     * Sets the value of the fileSystemStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileSystemStructure }
     *     
     */
    public void setFileSystemStructure(FileSystemStructure value) {
        this.fileSystemStructure = value;
    }

}
