//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 06:47:43 PM GMT 
//


package org.archenroot.fw.soatest.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 *                 Configuration related to DatabaseComponent part of the framework.
 *                 
 *                 Supported databases: Oracle
 *                 
 *                 Planned support for any database with generic JDBC interface available.
 *                 
 *             
 * 
 * <p>Java class for DatabaseConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatabaseConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectionIdentification" type="{http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration}ConnectionIdentification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatabaseConfiguration", namespace = "http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration", propOrder = {
    "connectionIdentification"
})
public class DatabaseConfiguration {

    @XmlElement(required = true)
    protected ConnectionIdentification connectionIdentification;

    /**
     * Gets the value of the connectionIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionIdentification }
     *     
     */
    public ConnectionIdentification getConnectionIdentification() {
        return connectionIdentification;
    }

    /**
     * Sets the value of the connectionIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionIdentification }
     *     
     */
    public void setConnectionIdentification(ConnectionIdentification value) {
        this.connectionIdentification = value;
    }

}
