//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 06:47:43 PM GMT 
//


package org.archenroot.fw.soatest.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.archenroot.nodefaultnamespaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoaTestingFramework_QNAME = new QName("http://www.archenroot.org/SoaTestingFramework", "soaTestingFramework");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.archenroot.nodefaultnamespaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoaTestingFramework }
     * 
     */
    public SoaTestingFramework createSoaTestingFramework() {
        return new SoaTestingFramework();
    }

    /**
     * Create an instance of {@link DatabaseConfiguration }
     * 
     */
    public DatabaseConfiguration createDatabaseConfiguration() {
        return new DatabaseConfiguration();
    }

    /**
     * Create an instance of {@link ConnectionIdentification }
     * 
     */
    public ConnectionIdentification createConnectionIdentification() {
        return new ConnectionIdentification();
    }

    /**
     * Create an instance of {@link FileConfiguation }
     * 
     */
    public FileConfiguation createFileConfiguation() {
        return new FileConfiguation();
    }

    /**
     * Create an instance of {@link FtpConfiguration }
     * 
     */
    public FtpConfiguration createFtpConfiguration() {
        return new FtpConfiguration();
    }

    /**
     * Create an instance of {@link GlobalConfiguration }
     * 
     */
    public GlobalConfiguration createGlobalConfiguration() {
        return new GlobalConfiguration();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link Queue }
     * 
     */
    public Queue createQueue() {
        return new Queue();
    }

    /**
     * Create an instance of {@link JmsConfiguration }
     * 
     */
    public JmsConfiguration createJmsConfiguration() {
        return new JmsConfiguration();
    }

    /**
     * Create an instance of {@link Server }
     * 
     */
    public Server createServer() {
        return new Server();
    }

    /**
     * Create an instance of {@link MappingConfiguration }
     * 
     */
    public MappingConfiguration createMappingConfiguration() {
        return new MappingConfiguration();
    }

    /**
     * Create an instance of {@link ManagedServer }
     * 
     */
    public ManagedServer createManagedServer() {
        return new ManagedServer();
    }

    /**
     * Create an instance of {@link AdminServer }
     * 
     */
    public AdminServer createAdminServer() {
        return new AdminServer();
    }

    /**
     * Create an instance of {@link OsbConfiguration }
     * 
     */
    public OsbConfiguration createOsbConfiguration() {
        return new OsbConfiguration();
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link ServiceIdentification }
     * 
     */
    public ServiceIdentification createServiceIdentification() {
        return new ServiceIdentification();
    }

    /**
     * Create an instance of {@link SoapConfiguration }
     * 
     */
    public SoapConfiguration createSoapConfiguration() {
        return new SoapConfiguration();
    }

    /**
     * Create an instance of {@link ToolConfiguration }
     * 
     */
    public ToolConfiguration createToolConfiguration() {
        return new ToolConfiguration();
    }

    /**
     * Create an instance of {@link XmlConfiguration }
     * 
     */
    public XmlConfiguration createXmlConfiguration() {
        return new XmlConfiguration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoaTestingFramework }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.archenroot.org/SoaTestingFramework", name = "soaTestingFramework")
    public JAXBElement<SoaTestingFramework> createSoaTestingFramework(SoaTestingFramework value) {
        return new JAXBElement<SoaTestingFramework>(_SoaTestingFramework_QNAME, SoaTestingFramework.class, null, value);
    }

}
