//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 06:47:43 PM GMT 
//


package org.archenroot.fw.soatest.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OsbConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OsbConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adminServer" type="{http://www.archenroot.org/SoaTestingFramework/OsbConfiguration}AdminServer"/>
 *         &lt;element name="cluster" type="{http://www.archenroot.org/SoaTestingFramework/OsbConfiguration}Cluster"/>
 *         &lt;element name="connectionProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OsbConfiguration", namespace = "http://www.archenroot.org/SoaTestingFramework/OsbConfiguration", propOrder = {
    "adminServer",
    "cluster",
    "connectionProtocol"
})
public class OsbConfiguration {

    @XmlElement(required = true)
    protected AdminServer adminServer;
    @XmlElement(required = true)
    protected Cluster cluster;
    @XmlElement(required = true, defaultValue = "t3")
    protected String connectionProtocol;

    /**
     * Gets the value of the adminServer property.
     * 
     * @return
     *     possible object is
     *     {@link AdminServer }
     *     
     */
    public AdminServer getAdminServer() {
        return adminServer;
    }

    /**
     * Sets the value of the adminServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminServer }
     *     
     */
    public void setAdminServer(AdminServer value) {
        this.adminServer = value;
    }

    /**
     * Gets the value of the cluster property.
     * 
     * @return
     *     possible object is
     *     {@link Cluster }
     *     
     */
    public Cluster getCluster() {
        return cluster;
    }

    /**
     * Sets the value of the cluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cluster }
     *     
     */
    public void setCluster(Cluster value) {
        this.cluster = value;
    }

    /**
     * Gets the value of the connectionProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionProtocol() {
        return connectionProtocol;
    }

    /**
     * Sets the value of the connectionProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionProtocol(String value) {
        this.connectionProtocol = value;
    }

}
