//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href", namespaceURI = "http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.29 at 06:47:43 PM GMT 
//
@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.archenroot.org/SoaTestingFramework",
        xmlns = {
            @XmlNs(prefix = "stf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework"),
            @XmlNs(prefix = "dbconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration"),
            @XmlNs(prefix = "common", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/Common"),
            @XmlNs(prefix = "fileconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/FileConfiguation"),
            @XmlNs(prefix = "ftpconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/FtpConfiguration"),
            @XmlNs(prefix = "globconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/GlobalConfiguration"),
            @XmlNs(prefix = "jmsconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/JmsConfiguration"),
            @XmlNs(prefix = "mapconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/MappingConfiguration"),
            @XmlNs(prefix = "osbconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/OsbConfiguration"),
            @XmlNs(prefix = "soapconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/SoapConfiguration"),
            @XmlNs(prefix = "toolconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/ToolConfiguration"),
            @XmlNs(prefix = "xmlconf", namespaceURI = "http://www.archenroot.org/SoaTestingFramework/XmlConfiguration")
        },
        elementFormDefault = XmlNsForm.QUALIFIED,
        attributeFormDefault = XmlNsForm.UNQUALIFIED
)

package org.archenroot.fw.soatest.configuration;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
