//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.01 at 05:24:47 PM BST 
//


package com.ibm.fm.soatest.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 *                 SOAP protocol configuration.
 * 
 *                 Currently only transport over HTTP protocol supported!
 *                 
 *                 SMTP and JMS protocol should be supported in future.
 *                 
 *             
 * 
 * <p>Java class for ServiceIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceIdentification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endPointUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wsdlUriSuffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestMessageXmlFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseMessageXmlFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceIdentification", namespace = "http://www.archenroot.org/SoaTestingFramework/SoapConfiguration", propOrder = {
    "serviceName",
    "endPointUri",
    "wsdlUriSuffix",
    "operationName",
    "requestName",
    "requestMessageXmlFile",
    "responseMessageXmlFile"
})
public class ServiceIdentification {

    @XmlElement(required = true)
    protected String serviceName;
    @XmlElement(required = true)
    protected String endPointUri;
    @XmlElement(required = true, defaultValue = "?wsdl")
    protected String wsdlUriSuffix;
    @XmlElement(required = true)
    protected String operationName;
    @XmlElement(required = true)
    protected String requestName;
    @XmlElement(required = true)
    protected String requestMessageXmlFile;
    @XmlElement(required = true)
    protected String responseMessageXmlFile;

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the endPointUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPointUri() {
        return endPointUri;
    }

    /**
     * Sets the value of the endPointUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPointUri(String value) {
        this.endPointUri = value;
    }

    /**
     * Gets the value of the wsdlUriSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdlUriSuffix() {
        return wsdlUriSuffix;
    }

    /**
     * Sets the value of the wsdlUriSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdlUriSuffix(String value) {
        this.wsdlUriSuffix = value;
    }

    /**
     * Gets the value of the operationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * Sets the value of the operationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationName(String value) {
        this.operationName = value;
    }

    /**
     * Gets the value of the requestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestName() {
        return requestName;
    }

    /**
     * Sets the value of the requestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestName(String value) {
        this.requestName = value;
    }

    /**
     * Gets the value of the requestMessageXmlFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestMessageXmlFile() {
        return requestMessageXmlFile;
    }

    /**
     * Sets the value of the requestMessageXmlFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestMessageXmlFile(String value) {
        this.requestMessageXmlFile = value;
    }

    /**
     * Gets the value of the responseMessageXmlFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseMessageXmlFile() {
        return responseMessageXmlFile;
    }

    /**
     * Sets the value of the responseMessageXmlFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseMessageXmlFile(String value) {
        this.responseMessageXmlFile = value;
    }

}
