//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 02:56:41 PM BST 
//


package ibm.soatest.config.jmsconfiguration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.archenroot.soatestingframework.jmsconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.archenroot.soatestingframework.jmsconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Resources }
     * 
     */
    public Resources createResources() {
        return new Resources();
    }

    /**
     * Create an instance of {@link FileSystemStructure }
     * 
     */
    public FileSystemStructure createFileSystemStructure() {
        return new FileSystemStructure();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder }
     * 
     */
    public FileSystemStructure.RootFolder createFileSystemStructureRootFolder() {
        return new FileSystemStructure.RootFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.MessageFolder }
     * 
     */
    public FileSystemStructure.RootFolder.MessageFolder createFileSystemStructureRootFolderMessageFolder() {
        return new FileSystemStructure.RootFolder.MessageFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.SchemaFolder }
     * 
     */
    public FileSystemStructure.RootFolder.SchemaFolder createFileSystemStructureRootFolderSchemaFolder() {
        return new FileSystemStructure.RootFolder.SchemaFolder();
    }

    /**
     * Create an instance of {@link JMSModule }
     * 
     */
    public JMSModule createJMSModule() {
        return new JMSModule();
    }

    /**
     * Create an instance of {@link JMSServer }
     * 
     */
    public JMSServer createJMSServer() {
        return new JMSServer();
    }

    /**
     * Create an instance of {@link org.archenroot.soatestingframework.jmsconfiguration.Topic }
     * 
     */
    public ibm.soatest.config.jmsconfiguration.Topic createTopic() {
        return new ibm.soatest.config.jmsconfiguration.Topic();
    }

    /**
     * Create an instance of {@link org.archenroot.soatestingframework.jmsconfiguration.Queue }
     * 
     */
    public ibm.soatest.config.jmsconfiguration.Queue createQueue() {
        return new ibm.soatest.config.jmsconfiguration.Queue();
    }

    /**
     * Create an instance of {@link JmsConfiguration }
     * 
     */
    public JmsConfiguration createJmsConfiguration() {
        return new JmsConfiguration();
    }

    /**
     * Create an instance of {@link Resources.ConnectionFactory }
     * 
     */
    public Resources.ConnectionFactory createResourcesConnectionFactory() {
        return new Resources.ConnectionFactory();
    }

    /**
     * Create an instance of {@link Resources.Queue }
     * 
     */
    public Resources.Queue createResourcesQueue() {
        return new Resources.Queue();
    }

    /**
     * Create an instance of {@link Resources.Topic }
     * 
     */
    public Resources.Topic createResourcesTopic() {
        return new Resources.Topic();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.MessageFolder.MessageFile }
     * 
     */
    public FileSystemStructure.RootFolder.MessageFolder.MessageFile createFileSystemStructureRootFolderMessageFolderMessageFile() {
        return new FileSystemStructure.RootFolder.MessageFolder.MessageFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.SchemaFolder.SchemaFile }
     * 
     */
    public FileSystemStructure.RootFolder.SchemaFolder.SchemaFile createFileSystemStructureRootFolderSchemaFolderSchemaFile() {
        return new FileSystemStructure.RootFolder.SchemaFolder.SchemaFile();
    }

}
