//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileSystemStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileSystemStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rootFolder">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="schemaFolder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="schema" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="requestEnvelopeFolder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="requestEnvelopeFile">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request.xml" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="responseEnvelopeFolder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="responseEnvelopeFile">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response.xml" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="deleteStatementFolder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="deleteStatementFile">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete.sql" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="soap" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileSystemStructure", propOrder = {
    "rootFolder"
})
public class FileSystemStructure {

    @XmlElement(required = true)
    protected FileSystemStructure.RootFolder rootFolder;

    /**
     * Gets the value of the rootFolder property.
     * 
     * @return
     *     possible object is
     *     {@link FileSystemStructure.RootFolder }
     *     
     */
    public FileSystemStructure.RootFolder getRootFolder() {
        return rootFolder;
    }

    /**
     * Sets the value of the rootFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileSystemStructure.RootFolder }
     *     
     */
    public void setRootFolder(FileSystemStructure.RootFolder value) {
        this.rootFolder = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="schemaFolder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="schema" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="requestEnvelopeFolder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="requestEnvelopeFile">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request.xml" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="responseEnvelopeFolder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="responseEnvelopeFile">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response.xml" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="deleteStatementFolder">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="deleteStatementFile">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete.sql" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="soap" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schemaFolder",
        "requestEnvelopeFolder",
        "responseEnvelopeFolder",
        "deleteStatementFolder"
    })
    public static class RootFolder {

        @XmlElement(required = true)
        protected FileSystemStructure.RootFolder.SchemaFolder schemaFolder;
        @XmlElement(required = true)
        protected FileSystemStructure.RootFolder.RequestEnvelopeFolder requestEnvelopeFolder;
        @XmlElement(required = true)
        protected FileSystemStructure.RootFolder.ResponseEnvelopeFolder responseEnvelopeFolder;
        @XmlElement(required = true)
        protected FileSystemStructure.RootFolder.DeleteStatementFolder deleteStatementFolder;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the schemaFolder property.
         * 
         * @return
         *     possible object is
         *     {@link FileSystemStructure.RootFolder.SchemaFolder }
         *     
         */
        public FileSystemStructure.RootFolder.SchemaFolder getSchemaFolder() {
            return schemaFolder;
        }

        /**
         * Sets the value of the schemaFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileSystemStructure.RootFolder.SchemaFolder }
         *     
         */
        public void setSchemaFolder(FileSystemStructure.RootFolder.SchemaFolder value) {
            this.schemaFolder = value;
        }

        /**
         * Gets the value of the requestEnvelopeFolder property.
         * 
         * @return
         *     possible object is
         *     {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder }
         *     
         */
        public FileSystemStructure.RootFolder.RequestEnvelopeFolder getRequestEnvelopeFolder() {
            return requestEnvelopeFolder;
        }

        /**
         * Sets the value of the requestEnvelopeFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder }
         *     
         */
        public void setRequestEnvelopeFolder(FileSystemStructure.RootFolder.RequestEnvelopeFolder value) {
            this.requestEnvelopeFolder = value;
        }

        /**
         * Gets the value of the responseEnvelopeFolder property.
         * 
         * @return
         *     possible object is
         *     {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder }
         *     
         */
        public FileSystemStructure.RootFolder.ResponseEnvelopeFolder getResponseEnvelopeFolder() {
            return responseEnvelopeFolder;
        }

        /**
         * Sets the value of the responseEnvelopeFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder }
         *     
         */
        public void setResponseEnvelopeFolder(FileSystemStructure.RootFolder.ResponseEnvelopeFolder value) {
            this.responseEnvelopeFolder = value;
        }

        /**
         * Gets the value of the deleteStatementFolder property.
         * 
         * @return
         *     possible object is
         *     {@link FileSystemStructure.RootFolder.DeleteStatementFolder }
         *     
         */
        public FileSystemStructure.RootFolder.DeleteStatementFolder getDeleteStatementFolder() {
            return deleteStatementFolder;
        }

        /**
         * Sets the value of the deleteStatementFolder property.
         * 
         * @param value
         *     allowed object is
         *     {@link FileSystemStructure.RootFolder.DeleteStatementFolder }
         *     
         */
        public void setDeleteStatementFolder(FileSystemStructure.RootFolder.DeleteStatementFolder value) {
            this.deleteStatementFolder = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "soap";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="deleteStatementFile">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete.sql" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "deleteStatementFile"
        })
        public static class DeleteStatementFolder {

            @XmlElement(required = true)
            protected FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile deleteStatementFile;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the deleteStatementFile property.
             * 
             * @return
             *     possible object is
             *     {@link FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile }
             *     
             */
            public FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile getDeleteStatementFile() {
                return deleteStatementFile;
            }

            /**
             * Sets the value of the deleteStatementFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile }
             *     
             */
            public void setDeleteStatementFile(FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile value) {
                this.deleteStatementFile = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                if (name == null) {
                    return "delete";
                } else {
                    return name;
                }
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="delete.sql" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class DeleteStatementFile {

                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    if (name == null) {
                        return "delete.sql";
                    } else {
                        return name;
                    }
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="requestEnvelopeFile">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request.xml" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "requestEnvelopeFile"
        })
        public static class RequestEnvelopeFolder {

            @XmlElement(required = true)
            protected FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile requestEnvelopeFile;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the requestEnvelopeFile property.
             * 
             * @return
             *     possible object is
             *     {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile }
             *     
             */
            public FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile getRequestEnvelopeFile() {
                return requestEnvelopeFile;
            }

            /**
             * Sets the value of the requestEnvelopeFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile }
             *     
             */
            public void setRequestEnvelopeFile(FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile value) {
                this.requestEnvelopeFile = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                if (name == null) {
                    return "request";
                } else {
                    return name;
                }
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="request.xml" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class RequestEnvelopeFile {

                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    if (name == null) {
                        return "request.xml";
                    } else {
                        return name;
                    }
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="responseEnvelopeFile">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response.xml" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "responseEnvelopeFile"
        })
        public static class ResponseEnvelopeFolder {

            @XmlElement(required = true)
            protected FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile responseEnvelopeFile;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the responseEnvelopeFile property.
             * 
             * @return
             *     possible object is
             *     {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile }
             *     
             */
            public FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile getResponseEnvelopeFile() {
                return responseEnvelopeFile;
            }

            /**
             * Sets the value of the responseEnvelopeFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile }
             *     
             */
            public void setResponseEnvelopeFile(FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile value) {
                this.responseEnvelopeFile = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                if (name == null) {
                    return "response";
                } else {
                    return name;
                }
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="response.xml" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ResponseEnvelopeFile {

                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    if (name == null) {
                        return "response.xml";
                    } else {
                        return name;
                    }
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="schema" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SchemaFolder {

            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                if (name == null) {
                    return "schema";
                } else {
                    return name;
                }
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
