//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 02:56:41 PM BST 
//


package ibm.soatest.config.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.archenroot.soatestingframework.soapconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.archenroot.soatestingframework.soapconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileSystemStructure }
     * 
     */
    public FileSystemStructure createFileSystemStructure() {
        return new FileSystemStructure();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder }
     * 
     */
    public FileSystemStructure.RootFolder createFileSystemStructureRootFolder() {
        return new FileSystemStructure.RootFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.DeleteStatementFolder }
     * 
     */
    public FileSystemStructure.RootFolder.DeleteStatementFolder createFileSystemStructureRootFolderDeleteStatementFolder() {
        return new FileSystemStructure.RootFolder.DeleteStatementFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder }
     * 
     */
    public FileSystemStructure.RootFolder.ResponseEnvelopeFolder createFileSystemStructureRootFolderResponseEnvelopeFolder() {
        return new FileSystemStructure.RootFolder.ResponseEnvelopeFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder }
     * 
     */
    public FileSystemStructure.RootFolder.RequestEnvelopeFolder createFileSystemStructureRootFolderRequestEnvelopeFolder() {
        return new FileSystemStructure.RootFolder.RequestEnvelopeFolder();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link SoapConfiguration }
     * 
     */
    public SoapConfiguration createSoapConfiguration() {
        return new SoapConfiguration();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.SchemaFolder }
     * 
     */
    public FileSystemStructure.RootFolder.SchemaFolder createFileSystemStructureRootFolderSchemaFolder() {
        return new FileSystemStructure.RootFolder.SchemaFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile }
     * 
     */
    public FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile createFileSystemStructureRootFolderDeleteStatementFolderDeleteStatementFile() {
        return new FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile }
     * 
     */
    public FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile createFileSystemStructureRootFolderResponseEnvelopeFolderResponseEnvelopeFile() {
        return new FileSystemStructure.RootFolder.ResponseEnvelopeFolder.ResponseEnvelopeFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile }
     * 
     */
    public FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile createFileSystemStructureRootFolderRequestEnvelopeFolderRequestEnvelopeFile() {
        return new FileSystemStructure.RootFolder.RequestEnvelopeFolder.RequestEnvelopeFile();
    }

}
