//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 
 *                 SOAP protocol configuration.
 * 
 *                 Currently only transport over HTTP protocol supported!
 *                 
 *                 SMTP and JMS protocol should be supported in future.
 *                 
 *             
 * 
 * <p>Java class for SOAPConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SOAPConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="service" type="{http://www.archenroot.org/SOATestingFramework/Config/SOAP}Service"/>
 *         &lt;element name="fileSystemStructure" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SOAPConfiguration", propOrder = {
    "service",
    "fileSystemStructure"
})
public class SOAPConfiguration {

    @XmlElement(required = true)
    protected Service service;
    @XmlElement(required = true)
    protected Object fileSystemStructure;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link Service }
     *     
     */
    public Service getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link Service }
     *     
     */
    public void setService(Service value) {
        this.service = value;
    }

    /**
     * Gets the value of the fileSystemStructure property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFileSystemStructure() {
        return fileSystemStructure;
    }

    /**
     * Sets the value of the fileSystemStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFileSystemStructure(Object value) {
        this.fileSystemStructure = value;
    }

}
