//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config.database;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ibm.soatest.config.database package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ibm.soatest.config.database
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Objects }
     * 
     */
    public Objects createObjects() {
        return new Objects();
    }

    /**
     * Create an instance of {@link FileSystemStructure }
     * 
     */
    public FileSystemStructure createFileSystemStructure() {
        return new FileSystemStructure();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder }
     * 
     */
    public FileSystemStructure.RootFolder createFileSystemStructureRootFolder() {
        return new FileSystemStructure.RootFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.DeleteStatementFolder }
     * 
     */
    public FileSystemStructure.RootFolder.DeleteStatementFolder createFileSystemStructureRootFolderDeleteStatementFolder() {
        return new FileSystemStructure.RootFolder.DeleteStatementFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.UpdateStatementFolder }
     * 
     */
    public FileSystemStructure.RootFolder.UpdateStatementFolder createFileSystemStructureRootFolderUpdateStatementFolder() {
        return new FileSystemStructure.RootFolder.UpdateStatementFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.InsertStatementFolder }
     * 
     */
    public FileSystemStructure.RootFolder.InsertStatementFolder createFileSystemStructureRootFolderInsertStatementFolder() {
        return new FileSystemStructure.RootFolder.InsertStatementFolder();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.SelectStatementFolder }
     * 
     */
    public FileSystemStructure.RootFolder.SelectStatementFolder createFileSystemStructureRootFolderSelectStatementFolder() {
        return new FileSystemStructure.RootFolder.SelectStatementFolder();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link DatabaseConfiguration }
     * 
     */
    public DatabaseConfiguration createDatabaseConfiguration() {
        return new DatabaseConfiguration();
    }

    /**
     * Create an instance of {@link Objects.Object }
     * 
     */
    public Objects.Object createObjectsObject() {
        return new Objects.Object();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile }
     * 
     */
    public FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile createFileSystemStructureRootFolderDeleteStatementFolderDeleteStatementFile() {
        return new FileSystemStructure.RootFolder.DeleteStatementFolder.DeleteStatementFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.UpdateStatementFolder.UpdateStatementFile }
     * 
     */
    public FileSystemStructure.RootFolder.UpdateStatementFolder.UpdateStatementFile createFileSystemStructureRootFolderUpdateStatementFolderUpdateStatementFile() {
        return new FileSystemStructure.RootFolder.UpdateStatementFolder.UpdateStatementFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.InsertStatementFolder.InsertStatementFile }
     * 
     */
    public FileSystemStructure.RootFolder.InsertStatementFolder.InsertStatementFile createFileSystemStructureRootFolderInsertStatementFolderInsertStatementFile() {
        return new FileSystemStructure.RootFolder.InsertStatementFolder.InsertStatementFile();
    }

    /**
     * Create an instance of {@link FileSystemStructure.RootFolder.SelectStatementFolder.SelectStatementFile }
     * 
     */
    public FileSystemStructure.RootFolder.SelectStatementFolder.SelectStatementFile createFileSystemStructureRootFolderSelectStatementFolderSelectStatementFile() {
        return new FileSystemStructure.RootFolder.SelectStatementFolder.SelectStatementFile();
    }

}
