//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 12:11:36 PM BST 
//


package ibm.soatest.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Attribute identificator is used for execution of framework component command or which object will be used for execution of the supported command.
 * 
 * <p>Java class for AdminServer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdminServer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jmxProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="securityPrincipal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="securityCredentials" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdminServer", namespace = "http://www.archenroot.org/SOATestingFramework/Config/OSB", propOrder = {
    "jmxProtocol",
    "host",
    "port",
    "securityPrincipal",
    "securityCredentials"
})
public class AdminServer {

    @XmlElement(required = true, defaultValue = "t3")
    protected String jmxProtocol;
    @XmlElement(required = true)
    protected String host;
    protected int port;
    @XmlElement(required = true)
    protected String securityPrincipal;
    @XmlElement(required = true)
    protected String securityCredentials;

    /**
     * Gets the value of the jmxProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmxProtocol() {
        return jmxProtocol;
    }

    /**
     * Sets the value of the jmxProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmxProtocol(String value) {
        this.jmxProtocol = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    public int getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    public void setPort(int value) {
        this.port = value;
    }

    /**
     * Gets the value of the securityPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityPrincipal() {
        return securityPrincipal;
    }

    /**
     * Sets the value of the securityPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityPrincipal(String value) {
        this.securityPrincipal = value;
    }

    /**
     * Gets the value of the securityCredentials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCredentials() {
        return securityCredentials;
    }

    /**
     * Sets the value of the securityCredentials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCredentials(String value) {
        this.securityCredentials = value;
    }

}
