//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.21 at 09:38:45 AM CEST 
//


package ibm.soatest.config;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComponentTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ComponentTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Database"/>
 *     &lt;enumeration value="JMS"/>
 *     &lt;enumeration value="File"/>
 *     &lt;enumeration value="Soap"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ComponentTypeEnum", namespace = "http://www.archenroot.org/SOATestingFramework/Config/Mapping")
@XmlEnum
public enum ComponentTypeEnum {

    @XmlEnumValue("Database")
    DATABASE("Database"),
    @XmlEnumValue("JMS")
    JMS("JMS"),
    @XmlEnumValue("File")
    FILE("File"),
    @XmlEnumValue("Soap")
    SOAP("Soap");
    private final String value;

    ComponentTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComponentTypeEnum fromValue(String v) {
        for (ComponentTypeEnum c: ComponentTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
