//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.01 at 05:24:47 PM BST 
//


package ibm.soatest.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Database configuration element node.
 * 
 * <p>Java class for Database complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Database">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="databaseType" type="{http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration}DatabaseTypeEnum"/>
 *         &lt;element name="driverClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="connectAs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="objectName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="insertSqlScriptFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="selectSqlScriptFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updateSqlScriptFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deleteSqlScriptFileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="identificator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Database", namespace = "http://www.archenroot.org/SoaTestingFramework/DatabaseConfiguration", propOrder = {
    "databaseType",
    "driverClassName",
    "hostName",
    "port",
    "userName",
    "password",
    "serviceId",
    "connectAs",
    "objectName",
    "insertSqlScriptFileName",
    "selectSqlScriptFileName",
    "updateSqlScriptFileName",
    "deleteSqlScriptFileName"
})
public class Database {

    @XmlElement(required = true)
    protected DatabaseTypeEnum databaseType;
    @XmlElement(required = true)
    protected String driverClassName;
    @XmlElement(required = true)
    protected String hostName;
    @XmlElement(required = true)
    protected BigInteger port;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(required = true)
    protected String serviceId;
    protected String connectAs;
    protected String objectName;
    protected String insertSqlScriptFileName;
    protected String selectSqlScriptFileName;
    protected String updateSqlScriptFileName;
    protected String deleteSqlScriptFileName;
    @XmlAttribute(name = "identificator")
    protected String identificator;

    /**
     * Gets the value of the databaseType property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseTypeEnum }
     *     
     */
    public DatabaseTypeEnum getDatabaseType() {
        return databaseType;
    }

    /**
     * Sets the value of the databaseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseTypeEnum }
     *     
     */
    public void setDatabaseType(DatabaseTypeEnum value) {
        this.databaseType = value;
    }

    /**
     * Gets the value of the driverClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverClassName() {
        return driverClassName;
    }

    /**
     * Sets the value of the driverClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverClassName(String value) {
        this.driverClassName = value;
    }

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPort(BigInteger value) {
        this.port = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the connectAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectAs() {
        return connectAs;
    }

    /**
     * Sets the value of the connectAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectAs(String value) {
        this.connectAs = value;
    }

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the insertSqlScriptFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertSqlScriptFileName() {
        return insertSqlScriptFileName;
    }

    /**
     * Sets the value of the insertSqlScriptFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertSqlScriptFileName(String value) {
        this.insertSqlScriptFileName = value;
    }

    /**
     * Gets the value of the selectSqlScriptFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectSqlScriptFileName() {
        return selectSqlScriptFileName;
    }

    /**
     * Sets the value of the selectSqlScriptFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectSqlScriptFileName(String value) {
        this.selectSqlScriptFileName = value;
    }

    /**
     * Gets the value of the updateSqlScriptFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateSqlScriptFileName() {
        return updateSqlScriptFileName;
    }

    /**
     * Sets the value of the updateSqlScriptFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateSqlScriptFileName(String value) {
        this.updateSqlScriptFileName = value;
    }

    /**
     * Gets the value of the deleteSqlScriptFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteSqlScriptFileName() {
        return deleteSqlScriptFileName;
    }

    /**
     * Sets the value of the deleteSqlScriptFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteSqlScriptFileName(String value) {
        this.deleteSqlScriptFileName = value;
    }

    /**
     * Gets the value of the identificator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificator() {
        return identificator;
    }

    /**
     * Sets the value of the identificator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificator(String value) {
        this.identificator = value;
    }

}
