//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.21 at 09:38:45 AM CEST 
//


package ibm.soatest.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MappingConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MappingConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromComponent" type="{http://www.archenroot.org/SOATestingFramework/Config/Mapping}component"/>
 *         &lt;element name="toComponent" type="{http://www.archenroot.org/SOATestingFramework/Config/Mapping}component"/>
 *         &lt;element name="customMappings" type="{http://www.archenroot.org/SOATestingFramework/Config/Mapping}customMappings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="identificator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MappingConfiguration", namespace = "http://www.archenroot.org/SOATestingFramework/Config/Mapping", propOrder = {
    "fromComponent",
    "toComponent",
    "customMappings"
})
public class MappingConfiguration {

    @XmlElement(required = true)
    protected Component fromComponent;
    @XmlElement(required = true)
    protected Component toComponent;
    protected CustomMappings customMappings;
    @XmlAttribute(name = "identificator", required = true)
    protected String identificator;

    /**
     * Gets the value of the fromComponent property.
     * 
     * @return
     *     possible object is
     *     {@link Component }
     *     
     */
    public Component getFromComponent() {
        return fromComponent;
    }

    /**
     * Sets the value of the fromComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Component }
     *     
     */
    public void setFromComponent(Component value) {
        this.fromComponent = value;
    }

    /**
     * Gets the value of the toComponent property.
     * 
     * @return
     *     possible object is
     *     {@link Component }
     *     
     */
    public Component getToComponent() {
        return toComponent;
    }

    /**
     * Sets the value of the toComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Component }
     *     
     */
    public void setToComponent(Component value) {
        this.toComponent = value;
    }

    /**
     * Gets the value of the customMappings property.
     * 
     * @return
     *     possible object is
     *     {@link CustomMappings }
     *     
     */
    public CustomMappings getCustomMappings() {
        return customMappings;
    }

    /**
     * Sets the value of the customMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomMappings }
     *     
     */
    public void setCustomMappings(CustomMappings value) {
        this.customMappings = value;
    }

    /**
     * Gets the value of the identificator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificator() {
        return identificator;
    }

    /**
     * Sets the value of the identificator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificator(String value) {
        this.identificator = value;
    }

}
