//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 11:36:33 AM BST 
//


package ibm.soatest.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ibm.soatest.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoaTestingFrameworkConfiguration_QNAME = new QName("http://www.archenroot.org/SoaTestingFramework", "soaTestingFrameworkConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ibm.soatest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SOATestingFrameworkConfiguration }
     * 
     */
    public SOATestingFrameworkConfiguration createSoaTestingFrameworkConfiguration() {
        return new SOATestingFrameworkConfiguration();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SOATestingFrameworkConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.archenroot.org/SoaTestingFramework", name = "soaTestingFrameworkConfiguration")
    public JAXBElement<SOATestingFrameworkConfiguration> createSoaTestingFrameworkConfiguration(SOATestingFrameworkConfiguration value) {
        return new JAXBElement<SOATestingFrameworkConfiguration>(_SoaTestingFrameworkConfiguration_QNAME, SOATestingFrameworkConfiguration.class, null, value);
    }

}
