//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 12:53:47 PM CEST 
//


package ibm.soatest.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ibm.soatest.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoaTestingFrameworkConfiguration_QNAME = new QName("http://www.archenroot.org/SOATestingFramework/Config", "soaTestingFrameworkConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ibm.soatest.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link JMSConfiguration }
     * 
     */
    public JMSConfiguration createJMSConfiguration() {
        return new JMSConfiguration();
    }

    /**
     * Create an instance of {@link DbObject }
     * 
     */
    public DbObject createDbObject() {
        return new DbObject();
    }

    /**
     * Create an instance of {@link SOATestingFrameworkConfiguration }
     * 
     */
    public SOATestingFrameworkConfiguration createSOATestingFrameworkConfiguration() {
        return new SOATestingFrameworkConfiguration();
    }

    /**
     * Create an instance of {@link DbObjects }
     * 
     */
    public DbObjects createDbObjects() {
        return new DbObjects();
    }

    /**
     * Create an instance of {@link DatabaseConfiguration }
     * 
     */
    public DatabaseConfiguration createDatabaseConfiguration() {
        return new DatabaseConfiguration();
    }

    /**
     * Create an instance of {@link OSBConfiguration }
     * 
     */
    public OSBConfiguration createOSBConfiguration() {
        return new OSBConfiguration();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link AdminServer }
     * 
     */
    public AdminServer createAdminServer() {
        return new AdminServer();
    }

    /**
     * Create an instance of {@link ibm.soatest.config.ManagedServer }
     * 
     */
    public ibm.soatest.config.ManagedServer createManagedServer() {
        return new ibm.soatest.config.ManagedServer();
    }

    /**
     * Create an instance of {@link Cluster.ManagedServer }
     * 
     */
    public Cluster.ManagedServer createClusterManagedServer() {
        return new Cluster.ManagedServer();
    }

    /**
     * Create an instance of {@link JMSConfiguration.Server }
     * 
     */
    public JMSConfiguration.Server createJMSConfigurationServer() {
        return new JMSConfiguration.Server();
    }

    /**
     * Create an instance of {@link JMSConfiguration.ConnectionFactory }
     * 
     */
    public JMSConfiguration.ConnectionFactory createJMSConfigurationConnectionFactory() {
        return new JMSConfiguration.ConnectionFactory();
    }

    /**
     * Create an instance of {@link JMSConfiguration.MessageSchema }
     * 
     */
    public JMSConfiguration.MessageSchema createJMSConfigurationMessageSchema() {
        return new JMSConfiguration.MessageSchema();
    }

    /**
     * Create an instance of {@link JMSConfiguration.Queue }
     * 
     */
    public JMSConfiguration.Queue createJMSConfigurationQueue() {
        return new JMSConfiguration.Queue();
    }

    /**
     * Create an instance of {@link DbObject.CustomValue }
     * 
     */
    public DbObject.CustomValue createDbObjectCustomValue() {
        return new DbObject.CustomValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SOATestingFrameworkConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.archenroot.org/SOATestingFramework/Config", name = "soaTestingFrameworkConfiguration")
    public JAXBElement<SOATestingFrameworkConfiguration> createSoaTestingFrameworkConfiguration(SOATestingFrameworkConfiguration value) {
        return new JAXBElement<SOATestingFrameworkConfiguration>(_SoaTestingFrameworkConfiguration_QNAME, SOATestingFrameworkConfiguration.class, null, value);
    }

}
