//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 01:37:36 PM BST 
//


package ibm.soatest.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import ibm.soatest.config.database.DatabaseConfiguration;
import ibm.soatest.config.file.FileConfiguration;
import ibm.soatest.config.ftp.FTPConfiguration;
import ibm.soatest.config.global.GlobalConfiguration;
import ibm.soatest.config.jms.JMSConfiguration;
import ibm.soatest.config.mapping.MappingConfiguration;
import ibm.soatest.config.osb.OSBConfiguration;
import ibm.soatest.config.soap.SOAPConfiguration;
import ibm.soatest.config.tool.ToolConfiguration;
import ibm.soatest.config.xml.XMLConfiguration;


/**
 * <p>Java class for SOATestingFrameworkConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SOATestingFrameworkConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="global" type="{http://www.archenroot.org/SOATestingFramework/Config/Global}GlobalConfiguration" minOccurs="0"/>
 *         &lt;element name="database" type="{http://www.archenroot.org/SOATestingFramework/Config/Database}DatabaseConfiguration" minOccurs="0"/>
 *         &lt;element name="file" type="{http://www.archenroot.org/SOATestingFramework/Config/File}FileConfiguration" minOccurs="0"/>
 *         &lt;element name="ftp" type="{http://www.archenroot.org/SOATestingFramework/Config/FTP}FTPConfiguration" minOccurs="0"/>
 *         &lt;element name="jms" type="{http://www.archenroot.org/SOATestingFramework/Config/JMS}JMSConfiguration" minOccurs="0"/>
 *         &lt;element name="mapping" type="{http://www.archenroot.org/SOATestingFramework/Config/Mapping}MappingConfiguration" minOccurs="0"/>
 *         &lt;element name="osb" type="{http://www.archenroot.org/SOATestingFramework/Config/OSB}OSBConfiguration" minOccurs="0"/>
 *         &lt;element name="soap" type="{http://www.archenroot.org/SOATestingFramework/Config/SOAP}SOAPConfiguration" minOccurs="0"/>
 *         &lt;element name="tool" type="{http://www.archenroot.org/SOATestingFramework/Config/Tool}ToolConfiguration" minOccurs="0"/>
 *         &lt;element name="xml" type="{http://www.archenroot.org/SOATestingFramework/Config/XML}XMLConfiguration" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SOATestingFrameworkConfiguration", propOrder = {
    "global",
    "database",
    "file",
    "ftp",
    "jms",
    "mapping",
    "osb",
    "soap",
    "tool",
    "xml"
})
public class SOATestingFrameworkConfiguration {

    protected GlobalConfiguration global;
    protected DatabaseConfiguration database;
    protected FileConfiguration file;
    protected FTPConfiguration ftp;
    protected JMSConfiguration jms;
    protected MappingConfiguration mapping;
    protected OSBConfiguration osb;
    protected SOAPConfiguration soap;
    protected ToolConfiguration tool;
    protected XMLConfiguration xml;

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalConfiguration }
     *     
     */
    public GlobalConfiguration getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalConfiguration }
     *     
     */
    public void setGlobal(GlobalConfiguration value) {
        this.global = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseConfiguration }
     *     
     */
    public DatabaseConfiguration getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseConfiguration }
     *     
     */
    public void setDatabase(DatabaseConfiguration value) {
        this.database = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link FileConfiguration }
     *     
     */
    public FileConfiguration getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileConfiguration }
     *     
     */
    public void setFile(FileConfiguration value) {
        this.file = value;
    }

    /**
     * Gets the value of the ftp property.
     * 
     * @return
     *     possible object is
     *     {@link FTPConfiguration }
     *     
     */
    public FTPConfiguration getFtp() {
        return ftp;
    }

    /**
     * Sets the value of the ftp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FTPConfiguration }
     *     
     */
    public void setFtp(FTPConfiguration value) {
        this.ftp = value;
    }

    /**
     * Gets the value of the jms property.
     * 
     * @return
     *     possible object is
     *     {@link JMSConfiguration }
     *     
     */
    public JMSConfiguration getJms() {
        return jms;
    }

    /**
     * Sets the value of the jms property.
     * 
     * @param value
     *     allowed object is
     *     {@link JMSConfiguration }
     *     
     */
    public void setJms(JMSConfiguration value) {
        this.jms = value;
    }

    /**
     * Gets the value of the mapping property.
     * 
     * @return
     *     possible object is
     *     {@link MappingConfiguration }
     *     
     */
    public MappingConfiguration getMapping() {
        return mapping;
    }

    /**
     * Sets the value of the mapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingConfiguration }
     *     
     */
    public void setMapping(MappingConfiguration value) {
        this.mapping = value;
    }

    /**
     * Gets the value of the osb property.
     * 
     * @return
     *     possible object is
     *     {@link OSBConfiguration }
     *     
     */
    public OSBConfiguration getOsb() {
        return osb;
    }

    /**
     * Sets the value of the osb property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSBConfiguration }
     *     
     */
    public void setOsb(OSBConfiguration value) {
        this.osb = value;
    }

    /**
     * Gets the value of the soap property.
     * 
     * @return
     *     possible object is
     *     {@link SOAPConfiguration }
     *     
     */
    public SOAPConfiguration getSoap() {
        return soap;
    }

    /**
     * Sets the value of the soap property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOAPConfiguration }
     *     
     */
    public void setSoap(SOAPConfiguration value) {
        this.soap = value;
    }

    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link ToolConfiguration }
     *     
     */
    public ToolConfiguration getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolConfiguration }
     *     
     */
    public void setTool(ToolConfiguration value) {
        this.tool = value;
    }

    /**
     * Gets the value of the xml property.
     * 
     * @return
     *     possible object is
     *     {@link XMLConfiguration }
     *     
     */
    public XMLConfiguration getXml() {
        return xml;
    }

    /**
     * Sets the value of the xml property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLConfiguration }
     *     
     */
    public void setXml(XMLConfiguration value) {
        this.xml = value;
    }

}
